// TURF Festival — Sanity Import Script
// Voer uit met: node import.js
//
// Vereiste: npm install @sanity/client
// Pas HIERONDER je project ID en token aan

import { createClient } from '@sanity/client'
import { readFileSync } from 'fs'

// Laad .env bestand
const env = Object.fromEntries(
  readFileSync('.env', 'utf-8').split('\n').filter(l => l && !l.startsWith('#')).map(l => l.split('='))
)

const client = createClient({
  projectId: env.SANITY_PROJECT_ID,
  dataset: 'production',
  token: env.SANITY_TOKEN,
  apiVersion: '2024-01-01',
  useCdn: false,
})

// ─── THEMA'S ────────────────────────────────────────────────────────────────
const themas = [
  { _id: 'thema-talks', _type: 'thema', naam: 'TURF Talks', slug: 'talks', kleur: '#c8f53b', beschrijving: 'Conferenties, debatten en keynotes over de toekomst van kunst, muziek en technologie.' },
  { _id: 'thema-live',  _type: 'thema', naam: 'TURF Live',  slug: 'live',  kleur: '#3b8bf5', beschrijving: 'Live performances waar muziek, kunst en technologie samenkomen.' },
  { _id: 'thema-night', _type: 'thema', naam: 'TURF by Night', slug: 'night', kleur: '#9b3bf5', beschrijving: 'Het nachtprogramma met club nights, DJ sets en live acts.' },
]

// ─── LOCATIES ───────────────────────────────────────────────────────────────
const locaties = [
  { _id: 'loc-01', _type: 'locatie', naam: 'Chassé Theater',         adres: 'Claudius Prinsenlaan 8, Breda',      capaciteit: 800,  type: 'theater' },
  { _id: 'loc-02', _type: 'locatie', naam: 'Nieuwe Veste',           adres: 'Claudius Prinsenlaan 10, Breda',     capaciteit: 300,  type: 'theater' },
  { _id: 'loc-03', _type: 'locatie', naam: 'Paradox',                adres: 'Tilburgseweg 44, Breda',             capaciteit: 400,  type: 'club' },
  { _id: 'loc-04', _type: 'locatie', naam: 'Club Skûll',             adres: 'Keizerstraat 16, Breda',             capaciteit: 250,  type: 'club' },
  { _id: 'loc-05', _type: 'locatie', naam: 'Academie St. Joost',     adres: 'Mgr. Hopmansstraat 2, Breda',        capaciteit: 200,  type: 'galerie' },
  { _id: 'loc-06', _type: 'locatie', naam: 'Station Hall',           adres: 'Stationsplein 1, Breda',             capaciteit: 1200, type: 'overig' },
  { _id: 'loc-07', _type: 'locatie', naam: 'Turfschip',              adres: 'Havendijk 28, Breda',                capaciteit: 180,  type: 'overig' },
  { _id: 'loc-08', _type: 'locatie', naam: 'Boei 10',                adres: 'Havenmeesterweg 10, Breda',          capaciteit: 500,  type: 'club' },
  { _id: 'loc-09', _type: 'locatie', naam: 'Grand Café Uno',         adres: 'Grote Markt 1, Breda',               capaciteit: 150,  type: 'overig' },
  { _id: 'loc-10', _type: 'locatie', naam: 'Muziekgieterij',         adres: 'Tramsingel 61, Breda',               capaciteit: 350,  type: 'theater' },
  { _id: 'loc-11', _type: 'locatie', naam: 'De Centrale',            adres: 'Spinveld 49, Breda',                 capaciteit: 600,  type: 'club' },
  { _id: 'loc-12', _type: 'locatie', naam: 'Lantaarnpaal',           adres: 'Schoolstraat 12, Breda',             capaciteit: 120,  type: 'overig' },
  { _id: 'loc-13', _type: 'locatie', naam: 'Lokaal',                 adres: 'Vismarktstraat 5, Breda',            capaciteit: 100,  type: 'overig' },
  { _id: 'loc-14', _type: 'locatie', naam: 'Mex',                    adres: 'Molenstraat 22, Breda',              capaciteit: 200,  type: 'club' },
  { _id: 'loc-15', _type: 'locatie', naam: 'Wilhelminapark',         adres: 'Wilhelminapark, Breda',              capaciteit: 2000, type: 'outdoor' },
  { _id: 'loc-16', _type: 'locatie', naam: 'Mark',                   adres: 'De Mark, Breda',                     capaciteit: 5000, type: 'outdoor' },
  { _id: 'loc-17', _type: 'locatie', naam: 'Rat Verlegh Stadion',    adres: 'Olympiaweg 1, Breda',                capaciteit: 1800, type: 'outdoor' },
  { _id: 'loc-18', _type: 'locatie', naam: 'Doornbos',               adres: 'Doornboslaan, Breda',                capaciteit: 800,  type: 'outdoor' },
  { _id: 'loc-19', _type: 'locatie', naam: 'Schuytgraaf',            adres: 'Schuytgraaf 1, Breda',               capaciteit: 150,  type: 'galerie' },
  { _id: 'loc-20', _type: 'locatie', naam: 'De Zwaan',               adres: 'Reigerstraat 8, Breda',              capaciteit: 220,  type: 'club' },
]

// ─── SPREKERS ───────────────────────────────────────────────────────────────
const sprekers = [
  { _id: 'spr-01', _type: 'spreker', naam: 'Jana Kovač',       rol: 'Founder', organisatie: 'Nacht Collective · Rotterdam',       bio: 'Jana onderzoekt de politieke dimensie van nachtcultuur en clubmuziek in Europa.' },
  { _id: 'spr-02', _type: 'spreker', naam: 'Daan Vermeer',     rol: 'Researcher', organisatie: 'Creative Cities Lab · Utrecht',    bio: 'Daan doet veldonderzoek naar de relatie tussen stedelijk beleid en creatieve economie.' },
  { _id: 'spr-03', _type: 'spreker', naam: 'Yuki Tanaka',      rol: 'Sound Artist', organisatie: 'Tokyo / Breda',                  bio: 'Yuki combineert field recordings met elektronische compositie in haar audiovisuele werk.' },
  { _id: 'spr-04', _type: 'spreker', naam: 'Amara Diallo',     rol: 'DJ / Activist', organisatie: 'Rhythm Politics · Antwerpen',  bio: 'Amara zet de dancefloor in als platform voor sociale verandering.' },
  { _id: 'spr-05', _type: 'spreker', naam: 'Lars Hendriks',    rol: 'Architect', organisatie: 'Urban Sound Studio · Amsterdam',    bio: 'Lars ontwerpt ruimtes die geluid als primair architectonisch element gebruiken.' },
  { _id: 'spr-06', _type: 'spreker', naam: 'Sofia Blum',       rol: 'Creative Technologist', organisatie: 'Freelance · Berlijn',   bio: 'Sofia bouwt interactieve installaties op het snijvlak van AI en performancekunst.' },
  { _id: 'spr-07', _type: 'spreker', naam: 'Rens de Groot',    rol: 'Curator', organisatie: 'BKKC · Tilburg',                      bio: 'Rens curates programma\'s rondom digitale cultuur en nieuwe media.' },
  { _id: 'spr-08', _type: 'spreker', naam: 'Fatima El Idrissi',rol: 'Producer', organisatie: 'Studio Lakmoes · Breda',             bio: 'Fatima produceert club nights en festivals met focus op inclusiviteit en diversiteit.' },
  { _id: 'spr-09', _type: 'spreker', naam: 'Tom Bakker',       rol: 'DJ / Producer', organisatie: 'Independant · Breda',           bio: 'Tom is een van de meest gevraagde techno-dj\'s van de Benelux.' },
  { _id: 'spr-10', _type: 'spreker', naam: 'Ines Morales',     rol: 'Visual Artist', organisatie: 'Academie St. Joost · Breda',    bio: 'Ines maakt lichtinstallaties die de verhouding tussen lichaam en ruimte bevragen.' },
  { _id: 'spr-11', _type: 'spreker', naam: 'Kwame Asante',     rol: 'Music Journalist', organisatie: 'Gonzo Circus · Gent',        bio: 'Kwame schrijft over de globalisering van elektronische muziekcultuur.' },
  { _id: 'spr-12', _type: 'spreker', naam: 'Lena Fischer',     rol: 'Club Owner', organisatie: 'Tresor · Berlijn',                 bio: 'Lena deelt haar ervaringen met het runnen van een iconische club over 30 jaar.' },
  { _id: 'spr-13', _type: 'spreker', naam: 'Noor van Dijk',    rol: 'Policy Advisor', organisatie: 'Gemeente Breda',               bio: 'Noor werkt aan het nieuwe nachtbeleid van Breda als creatieve stad.' },
  { _id: 'spr-14', _type: 'spreker', naam: 'Sasha Petrov',     rol: 'Live Act', organisatie: 'Freelance · Amsterdam',              bio: 'Sasha\'s live sets zijn een ode aan de analoge synthesizer-cultuur van de jaren 80.' },
  { _id: 'spr-15', _type: 'spreker', naam: 'Miriam Osei',      rol: 'Researcher', organisatie: 'Erasmus Universiteit · Rotterdam', bio: 'Miriam onderzoekt de rol van muziek in de constructie van Afro-Europese identiteit.' },
]

// ─── EVENTS ─────────────────────────────────────────────────────────────────
const events = [
  // ── DAG 1 — Donderdag 26 november ──────────────────────────────────────
  { _id: 'evt-01', _type: 'event', titel: 'De Toekomst van Nachtcultuur',           dag: 'dag1', startTijd: '10:00', eindTijd: '11:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Keynote',      sprekers: [{ _type: 'reference', _ref: 'spr-01' }, { _type: 'reference', _ref: 'spr-13' }], tags: ['Nightlife', 'Policy', 'Urban'],       beschrijving: 'Wat betekent nachtcultuur voor de stad van morgen? Jana Kovač en Noor van Dijk verkennen de spanning tussen creatieve vrijheid en stedelijk beleid.', gepubliceerd: true },
  { _id: 'evt-02', _type: 'event', titel: 'AI & Creatieve Expressie',               dag: 'dag1', startTijd: '10:00', eindTijd: '11:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-06' }, { _type: 'reference', _ref: 'spr-07' }], tags: ['AI', 'Creativiteit', 'Technologie'], beschrijving: 'Hoe verandert artificiële intelligentie de manier waarop we kunst maken en ervaren? Een open gesprek met makers en onderzoekers.', gepubliceerd: true },
  { _id: 'evt-03', _type: 'event', titel: 'Lichtinstallatie: Pulse',                dag: 'dag1', startTijd: '10:00', eindTijd: '18:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-05' }, type: 'Installatie',  sprekers: [{ _type: 'reference', _ref: 'spr-10' }],                                            tags: ['Lichtkunst', 'Installatie'],         beschrijving: 'Een meeslepende lichtinstallatie die reageert op de bewegingen van bezoekers. Ines Morales transformeert de galerie in een levend organisme.', gepubliceerd: true },
  { _id: 'evt-04', _type: 'event', titel: 'Techno als Politieke Daad',              dag: 'dag1', startTijd: '12:00', eindTijd: '13:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-04' }, { _type: 'reference', _ref: 'spr-15' }], tags: ['Techno', 'Politiek', 'Activisme'],   beschrijving: 'De dancefloor als plek van verzet. Amara Diallo en Miriam Osei bespreken hoe muziek bijdraagt aan sociale bewegingen.', gepubliceerd: true },
  { _id: 'evt-05', _type: 'event', titel: 'Geluid & Architectuur',                  dag: 'dag1', startTijd: '12:00', eindTijd: '13:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Keynote',      sprekers: [{ _type: 'reference', _ref: 'spr-05' }],                                            tags: ['Architectuur', 'Sound Design'],      beschrijving: 'Lars Hendriks laat zien hoe hij akoestiek als primair ontwerpprincipe gebruikt bij het bouwen van culturele ruimtes.', gepubliceerd: true },
  { _id: 'evt-06', _type: 'event', titel: 'Workshop: Generatieve Muziek',           dag: 'dag1', startTijd: '14:00', eindTijd: '16:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-10' }, type: 'Workshop',     sprekers: [{ _type: 'reference', _ref: 'spr-06' }],                                            tags: ['Workshop', 'Generatief', 'Code'],    beschrijving: 'Leer hoe je met eenvoudige code je eigen generatieve muziekstukken maakt. Geen muzikale voorkennis vereist — wel een laptop meenemen.', gepubliceerd: true },
  { _id: 'evt-07', _type: 'event', titel: 'Digitale Identiteiten',                  dag: 'dag1', startTijd: '14:00', eindTijd: '15:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-11' }, { _type: 'reference', _ref: 'spr-07' }], tags: ['Identiteit', 'Digital', 'Cultuur'],  beschrijving: 'Hoe vormen online platforms onze culturele identiteit? En wat betekent dat voor de manier waarop we muziek en kunst consumeren?', gepubliceerd: true },
  { _id: 'evt-08', _type: 'event', titel: 'Urban Sound Mapping',                    dag: 'dag1', startTijd: '14:00', eindTijd: '17:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-16' }, type: 'Rondleiding',  sprekers: [{ _type: 'reference', _ref: 'spr-03' }],                                            tags: ['Stadswandeling', 'Sound Art'],       beschrijving: 'Een begeleide geluidswandeling door het centrum van Breda. Yuki Tanaka neemt je mee in de verborgen klankwereld van de stad.', gepubliceerd: true },
  { _id: 'evt-09', _type: 'event', titel: '30 jaar Clubcultuur: Lezing',            dag: 'dag1', startTijd: '16:00', eindTijd: '17:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Keynote',      sprekers: [{ _type: 'reference', _ref: 'spr-12' }],                                            tags: ['Clubcultuur', 'Geschiedenis'],       beschrijving: 'Lena Fischer vertelt over drie decennia Tresor — van een verlaten warenhuis tot een van de meest invloedrijke clubs ter wereld.', gepubliceerd: true },
  { _id: 'evt-10', _type: 'event', titel: 'Opening Night: TURF Live',               dag: 'dag1', startTijd: '20:00', eindTijd: '23:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-06' }, type: 'Performance',  sprekers: [{ _type: 'reference', _ref: 'spr-14' }, { _type: 'reference', _ref: 'spr-03' }], tags: ['Opening', 'Live', 'Audiovisueel'],   beschrijving: 'De feestelijke opening van TURF 2026 met een audiovisuele performance van Sasha Petrov en Yuki Tanaka. Gratis toegang voor alle festivalgangers.', gratis: true, gepubliceerd: true },
  { _id: 'evt-11', _type: 'event', titel: 'Club Night: Residents',                  dag: 'dag1', startTijd: '23:00', eindTijd: '05:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-03' }, type: 'Club Night',   sprekers: [{ _type: 'reference', _ref: 'spr-09' }, { _type: 'reference', _ref: 'spr-04' }], tags: ['Techno', 'Club', 'Nacht'],          beschrijving: 'De vaste Paradox residents openen het nachtprogramma van TURF. Tom Bakker en Amara Diallo draaien tegenover elkaar in een back-to-back formaat.', gepubliceerd: true },
  { _id: 'evt-12', _type: 'event', titel: 'Experimental Night: Club Skûll',         dag: 'dag1', startTijd: '23:00', eindTijd: '04:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-04' }, type: 'Club Night',   sprekers: [],                                                                                   tags: ['Experimental', 'Underground'],       beschrijving: 'Club Skûll opent haar deuren voor een nacht vol experimentele elektronische muziek en avant-garde DJ sets.', gepubliceerd: true },

  // ── DAG 2 — Vrijdag 27 november ────────────────────────────────────────
  { _id: 'evt-13', _type: 'event', titel: 'Inclusieve Dansvloeren',                 dag: 'dag2', startTijd: '10:00', eindTijd: '11:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-08' }, { _type: 'reference', _ref: 'spr-04' }], tags: ['Inclusiviteit', 'Diversiteit'],      beschrijving: 'Hoe maken we clubruimtes veiliger en inclusiever voor iedereen? Fatima El Idrissi en Amara Diallo delen concrete strategieën.', gepubliceerd: true },
  { _id: 'evt-14', _type: 'event', titel: 'Het Algoritme Speelt',                   dag: 'dag2', startTijd: '10:00', eindTijd: '11:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-02' }, { _type: 'reference', _ref: 'spr-11' }], tags: ['Streaming', 'Algoritme', 'Muziek'],  beschrijving: 'Spotify, Apple Music, TikTok — hoe bepalen algoritmen welke muziek we horen en welke artiesten doorbreken?', gepubliceerd: true },
  { _id: 'evt-15', _type: 'event', titel: 'Live Act: Sasha Petrov',                 dag: 'dag2', startTijd: '11:00', eindTijd: '12:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-10' }, type: 'Performance',  sprekers: [{ _type: 'reference', _ref: 'spr-14' }],                                            tags: ['Analoog', 'Synthesizer', 'Live'],    beschrijving: 'Een uniek live optreden waarbij Sasha Petrov uitsluitend werkt met vintage analoge synthesizers en een modulair systeem.', gepubliceerd: true },
  { _id: 'evt-16', _type: 'event', titel: 'Hardware Hacking voor Beginners',        dag: 'dag2', startTijd: '12:00', eindTijd: '14:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-07' }, type: 'Workshop',     sprekers: [{ _type: 'reference', _ref: 'spr-06' }],                                            tags: ['Workshop', 'Hardware', 'DIY'],       beschrijving: 'Bouw je eigen geluidsmachine van goedkope electronica-componenten. Materialen worden verstrekt, breng een schroevendraaier mee.', gepubliceerd: true },
  { _id: 'evt-17', _type: 'event', titel: 'Nachtbeleid in Europese Steden',         dag: 'dag2', startTijd: '12:00', eindTijd: '13:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-13' }, { _type: 'reference', _ref: 'spr-12' }], tags: ['Policy', 'Europa', 'Nightlife'],     beschrijving: 'Amsterdam, Berlijn, Londen, Breda — hoe verschillen Europese steden in hun aanpak van nachtcultuur als stedelijke functie?', gepubliceerd: true },
  { _id: 'evt-18', _type: 'event', titel: 'Field Recordings Sessie',                dag: 'dag2', startTijd: '12:00', eindTijd: '16:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-15' }, type: 'Workshop',     sprekers: [{ _type: 'reference', _ref: 'spr-03' }],                                            tags: ['Field Recording', 'Natuur', 'Sound'],beschrijving: 'Trek het Wilhelminapark in met een microfoon en leer hoe je omgevingsgeluiden kunt vastleggen en verwerken tot muziek.', gepubliceerd: true },
  { _id: 'evt-19', _type: 'event', titel: 'Vinyl & Geheugen',                       dag: 'dag2', startTijd: '14:00', eindTijd: '15:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-09' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-11' }, { _type: 'reference', _ref: 'spr-09' }], tags: ['Vinyl', 'Nostalgie', 'Cultuur'],     beschrijving: 'De vinylrevival is meer dan nostalgie. Kwame Asante en Tom Bakker bespreken waarom het fysieke medium aan relevantie wint.', gepubliceerd: true },
  { _id: 'evt-20', _type: 'event', titel: 'Presentatie: Creatief Breda 2030',       dag: 'dag2', startTijd: '14:00', eindTijd: '15:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Keynote',      sprekers: [{ _type: 'reference', _ref: 'spr-02' }, { _type: 'reference', _ref: 'spr-13' }], tags: ['Breda', 'Toekomst', 'Beleid'],       beschrijving: 'De gemeente Breda en Creative Cities Lab presenteren de gezamenlijke visie op Breda als creatieve stad van de toekomst.', gepubliceerd: true },
  { _id: 'evt-21', _type: 'event', titel: 'Open Source Beats',                      dag: 'dag2', startTijd: '15:00', eindTijd: '17:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-10' }, type: 'Workshop',     sprekers: [{ _type: 'reference', _ref: 'spr-09' }],                                            tags: ['Workshop', 'Productie', 'Open Source'],beschrijving: 'Tom Bakker laat zien hoe hij uitsluitend gratis en open source software gebruikt voor zijn producties. Live in Ableton op het podium.', gepubliceerd: true },
  { _id: 'evt-22', _type: 'event', titel: 'Drone Soundscape',                       dag: 'dag2', startTijd: '16:00', eindTijd: '17:30', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Performance',  sprekers: [{ _type: 'reference', _ref: 'spr-03' }, { _type: 'reference', _ref: 'spr-14' }], tags: ['Ambient', 'Drone', 'Performance'],   beschrijving: 'Yuki Tanaka en Sasha Petrov creëren samen een 90 minuten durend drone soundscape voor de grote zaal van het Chassé Theater.', gepubliceerd: true },
  { _id: 'evt-23', _type: 'event', titel: 'Pre-Party: Station Hall',                dag: 'dag2', startTijd: '19:00', eindTijd: '23:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-06' }, type: 'Showcase',     sprekers: [{ _type: 'reference', _ref: 'spr-08' }, { _type: 'reference', _ref: 'spr-07' }], tags: ['Showcase', 'Emerging', 'Talent'],    beschrijving: 'Vier opkomende Bredase artiesten en dj\'s krijgen elk 45 minuten om te laten zien wat ze kunnen. Curated door Fatima El Idrissi.', gepubliceerd: true },
  { _id: 'evt-24', _type: 'event', titel: 'TURF by Night: Boei 10',                 dag: 'dag2', startTijd: '23:00', eindTijd: '06:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-08' }, type: 'Club Night',   sprekers: [{ _type: 'reference', _ref: 'spr-04' }, { _type: 'reference', _ref: 'spr-01' }], tags: ['Techno', 'House', 'Nacht'],          beschrijving: 'De grootste club night van TURF 2026. Amara Diallo b2b met verrassingsgast op de hoofdvloer van Boei 10.', gepubliceerd: true },
  { _id: 'evt-25', _type: 'event', titel: 'Late Night: De Zwaan',                   dag: 'dag2', startTijd: '23:00', eindTijd: '05:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-20' }, type: 'Club Night',   sprekers: [],                                                                                   tags: ['House', 'Underground', 'Nacht'],     beschrijving: 'De Zwaan presenteert een intieme late night met focus op deep house en experimental club muziek.', gepubliceerd: true },
  { _id: 'evt-26', _type: 'event', titel: 'Paradox Nacht',                          dag: 'dag2', startTijd: '22:00', eindTijd: '04:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-03' }, type: 'Club Night',   sprekers: [{ _type: 'reference', _ref: 'spr-09' }],                                            tags: ['Techno', 'Club'],                    beschrijving: 'Tom Bakker speelt een uitgebreide set in zijn thuishaven Paradox. Support van lokale residents.', gepubliceerd: true },

  // ── DAG 3 — Zaterdag 28 november ───────────────────────────────────────
  { _id: 'evt-27', _type: 'event', titel: 'Duurzame Nachtcultuur',                  dag: 'dag3', startTijd: '10:00', eindTijd: '11:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-08' }, { _type: 'reference', _ref: 'spr-02' }], tags: ['Duurzaamheid', 'Milieu', 'Club'],    beschrijving: 'Van energieverbruik tot afvalbeleid: hoe kunnen clubs en festivals hun ecologische voetafdruk verkleinen zonder aan beleving in te boeten?', gepubliceerd: true },
  { _id: 'evt-28', _type: 'event', titel: 'Muziek & Afro-Europese Identiteit',      dag: 'dag3', startTijd: '10:00', eindTijd: '11:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-15' }, { _type: 'reference', _ref: 'spr-11' }], tags: ['Identiteit', 'Afrobeat', 'Europa'],  beschrijving: 'Miriam Osei en Kwame Asante bespreken hoe Afro-Europese artiesten elektronische muziek gebruiken om hun meervoudige identiteit te articuleren.', gepubliceerd: true },
  { _id: 'evt-29', _type: 'event', titel: 'Installatie: Echo Chamber',              dag: 'dag3', startTijd: '10:00', eindTijd: '18:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-19' }, type: 'Installatie',  sprekers: [{ _type: 'reference', _ref: 'spr-10' }, { _type: 'reference', _ref: 'spr-03' }], tags: ['Installatie', 'Immersief', 'Sound'],  beschrijving: 'Een interactieve geluidsinstallatie waarbij jouw stem de ruimte transformeert. Ines Morales en Yuki Tanaka creëren een meervoudige echo-ervaring.', gepubliceerd: true },
  { _id: 'evt-30', _type: 'event', titel: 'Closing Keynote: De Creatieve Stad',     dag: 'dag3', startTijd: '11:00', eindTijd: '12:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Keynote',      sprekers: [{ _type: 'reference', _ref: 'spr-01' }, { _type: 'reference', _ref: 'spr-02' }], tags: ['Toekomst', 'Stad', 'Cultuur'],       beschrijving: 'Jana Kovač en Daan Vermeer sluiten het inhoudelijke programma af met een doorkijk naar de uitdagingen en kansen voor creatieve steden in de komende tien jaar.', gepubliceerd: true },
  { _id: 'evt-31', _type: 'event', titel: 'Workshop: Ableton voor Beginners',       dag: 'dag3', startTijd: '12:00', eindTijd: '14:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-10' }, type: 'Workshop',     sprekers: [{ _type: 'reference', _ref: 'spr-08' }],                                            tags: ['Workshop', 'Ableton', 'Productie'],  beschrijving: 'Fatima El Idrissi neemt je in twee uur mee door de basisprincipes van muziekproductie in Ableton Live. Laptop vereist.', gepubliceerd: true },
  { _id: 'evt-32', _type: 'event', titel: 'Debat: Is de Dancefloor Politiek?',      dag: 'dag3', startTijd: '12:00', eindTijd: '13:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-04' }, { _type: 'reference', _ref: 'spr-12' }, { _type: 'reference', _ref: 'spr-15' }], tags: ['Debat', 'Politiek', 'Cultuur'], beschrijving: 'Een stevig debat over de vraag of clubcultuur intrinsiek politiek is, of dat dit een romantisering is van een commerciële vrijetijdsindustrie.', gepubliceerd: true },
  { _id: 'evt-33', _type: 'event', titel: 'Live: Yuki Tanaka',                      dag: 'dag3', startTijd: '14:00', eindTijd: '15:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-06' }, type: 'Performance',  sprekers: [{ _type: 'reference', _ref: 'spr-03' }],                                            tags: ['Live', 'Ambient', 'Audiovisueel'],   beschrijving: 'Yuki Tanaka\'s eerste grote live set in Nederland. Een audiovisuele performance gebaseerd op haar nieuwe album over stedelijke isolatie.', gepubliceerd: true },
  { _id: 'evt-34', _type: 'event', titel: 'Neon City Showcase',                     dag: 'dag3', startTijd: '14:00', eindTijd: '17:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-15' }, type: 'Showcase',     sprekers: [{ _type: 'reference', _ref: 'spr-07' }, { _type: 'reference', _ref: 'spr-05' }], tags: ['Outdoor', 'Showcase', 'Stad'],       beschrijving: 'Rens de Groot en Lars Hendriks presenteren een buitenshowcase waarbij zes jonge kunstenaars lichtkunst en geluid combineren in het Wilhelminapark.', gepubliceerd: true },
  { _id: 'evt-35', _type: 'event', titel: 'Gesprek: Breda & de Nacht',              dag: 'dag3', startTijd: '15:00', eindTijd: '16:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-09' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-13' }, { _type: 'reference', _ref: 'spr-08' }], tags: ['Breda', 'Nacht', 'Beleid'],          beschrijving: 'Noor van Dijk (gemeente) en Fatima El Idrissi (producent) in gesprek over de concrete plannen voor een levendiger nachtleven in Breda.', gepubliceerd: true },
  { _id: 'evt-36', _type: 'event', titel: 'Closing Party: Mark',                    dag: 'dag3', startTijd: '16:00', eindTijd: '23:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-16' }, type: 'Showcase',     sprekers: [{ _type: 'reference', _ref: 'spr-09' }, { _type: 'reference', _ref: 'spr-04' }, { _type: 'reference', _ref: 'spr-14' }], tags: ['Outdoor', 'Festival', 'Closing'], beschrijving: 'Het grote outdoor afsluitingsfestival op De Mark. Drie podia, zeven uur muziek, gratis toegang voor alle festivalgangers.', gratis: true, gepubliceerd: true },
  { _id: 'evt-37', _type: 'event', titel: 'TURF Final Night: Boei 10',              dag: 'dag3', startTijd: '23:00', eindTijd: '07:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-08' }, type: 'Club Night',   sprekers: [{ _type: 'reference', _ref: 'spr-12' }, { _type: 'reference', _ref: 'spr-04' }], tags: ['Techno', 'Final Night', 'Nacht'],    beschrijving: 'Lena Fischer sluit TURF 2026 af met een legendarische marathon set vanuit Berlijn. De laatste nacht van het festival — tot de ochtend.', gepubliceerd: true },
  { _id: 'evt-38', _type: 'event', titel: 'After: De Centrale',                     dag: 'dag3', startTijd: '23:30', eindTijd: '06:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-11' }, type: 'Club Night',   sprekers: [],                                                                                   tags: ['After', 'Underground', 'Nacht'],     beschrijving: 'De officieuze after-party van TURF 2026. Kom als de rest van de stad gaat slapen.', gepubliceerd: true },

  // ── Extra events om op 75 te komen ────────────────────────────────────
  { _id: 'evt-39', _type: 'event', titel: 'Community Radio: Live Uitzending',       dag: 'dag1', startTijd: '16:00', eindTijd: '18:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-12' }, type: 'Showcase',     sprekers: [{ _type: 'reference', _ref: 'spr-11' }], tags: ['Radio', 'Community', 'Live'],        beschrijving: 'TURF Radio zendt live uit vanuit het festival. Kwame Asante is gastheer en ontvangt muzikanten, kunstenaars en bezoekers.', gepubliceerd: true },
  { _id: 'evt-40', _type: 'event', titel: 'Paneldiscussie: Gaming & Muziek',        dag: 'dag1', startTijd: '15:00', eindTijd: '16:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-06' }, { _type: 'reference', _ref: 'spr-07' }], tags: ['Gaming', 'Muziek', 'Cultuur'],       beschrijving: 'Hoe beïnvloedt de gamecultuur hedendaagse elektronische muziek? Van chiptune tot hyperpop — de grenzen vervagen.', gepubliceerd: true },
  { _id: 'evt-41', _type: 'event', titel: 'Masterclass: Sound Design',              dag: 'dag2', startTijd: '10:00', eindTijd: '12:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-13' }, type: 'Workshop',     sprekers: [{ _type: 'reference', _ref: 'spr-14' }], tags: ['Sound Design', 'Masterclass'],       beschrijving: 'Sasha Petrov deelt zijn complete workflow voor sound design, van concept tot eindmix, met praktische oefeningen.', gepubliceerd: true },
  { _id: 'evt-42', _type: 'event', titel: 'Presentatie: Nieuwe Media Kunst',        dag: 'dag2', startTijd: '13:00', eindTijd: '14:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-05' }, type: 'Keynote',      sprekers: [{ _type: 'reference', _ref: 'spr-10' }], tags: ['Mediakunst', 'Digitaal'],            beschrijving: 'Ines Morales presenteert haar meest recente werk en de artistieke ontwikkeling achter haar lichtinstallaties.', gepubliceerd: true },
  { _id: 'evt-43', _type: 'event', titel: 'Netwerksessie: Muziekindustrie',         dag: 'dag2', startTijd: '17:00', eindTijd: '19:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-09' }, type: 'Workshop',     sprekers: [],                                        tags: ['Netwerken', 'Industrie'],            beschrijving: 'Informele netwerksessie voor muziekprofessionals, producenten, managers en journalisten. Drankje inbegrepen.', gepubliceerd: true },
  { _id: 'evt-44', _type: 'event', titel: 'Lezing: Rave Geschiedenis',              dag: 'dag1', startTijd: '11:00', eindTijd: '12:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-13' }, type: 'Keynote',      sprekers: [{ _type: 'reference', _ref: 'spr-12' }], tags: ['Rave', 'Geschiedenis', 'UK'],        beschrijving: 'Van de Haçienda tot de M25 raves — een historisch overzicht van de Britse ravebeweging en haar politieke erfenis.', gepubliceerd: true },
  { _id: 'evt-45', _type: 'event', titel: 'Workshop: Fotograferen op Festivals',    dag: 'dag1', startTijd: '13:00', eindTijd: '15:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-05' }, type: 'Workshop',     sprekers: [],                                        tags: ['Fotografie', 'Workshop'],            beschrijving: 'Leer hoe je in moeilijke lichtomstandigheden te fotograferen. Van dansvloer tot backstage — praktische tips voor festivaifotografen.', gepubliceerd: true },
  { _id: 'evt-46', _type: 'event', titel: 'Live: Ambient Set',                      dag: 'dag2', startTijd: '18:00', eindTijd: '19:30', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-07' }, type: 'Performance',  sprekers: [{ _type: 'reference', _ref: 'spr-03' }], tags: ['Ambient', 'Live', 'Intiem'],         beschrijving: 'Een intieme ambient set van Yuki Tanaka op de bovenetage van het Turfschip. Maximaal 80 bezoekers — aanmelden verplicht.', aanmelding: true, gepubliceerd: true },
  { _id: 'evt-47', _type: 'event', titel: 'Paneldiscussie: Vrouwen in Techno',      dag: 'dag3', startTijd: '13:00', eindTijd: '14:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-01' }, { _type: 'reference', _ref: 'spr-08' }, { _type: 'reference', _ref: 'spr-12' }], tags: ['Gender', 'Diversiteit', 'Techno'], beschrijving: 'Jana Kovač, Fatima El Idrissi en Lena Fischer bespreken de positie van vrouwen in de techno scene — van DJ booth tot festivalorganisatie.', gepubliceerd: true },
  { _id: 'evt-48', _type: 'event', titel: 'Screening: Documentaire Clubcultuur',    dag: 'dag3', startTijd: '11:00', eindTijd: '13:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Screening',    sprekers: [],                                        tags: ['Film', 'Documentaire', 'Club'],      beschrijving: 'Vertoning van een recent documentaire over de opkomst en ondergang van clubcultuur in drie Europese steden, gevolgd door Q&A.', gepubliceerd: true },
  { _id: 'evt-49', _type: 'event', titel: 'Expo: Digitale Kunstwerken',             dag: 'dag1', startTijd: '10:00', eindTijd: '20:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-05' }, type: 'Installatie',  sprekers: [{ _type: 'reference', _ref: 'spr-10' }, { _type: 'reference', _ref: 'spr-06' }], tags: ['Expo', 'Digitaal', 'Kunst'],         beschrijving: 'Een groepstentoonstelling met digitale en generatieve kunstwerken van zeven jonge makers. Doorlopend te bezoeken gedurende dag 1.', gepubliceerd: true },
  { _id: 'evt-50', _type: 'event', titel: 'Expo: Digitale Kunstwerken (dag 2)',     dag: 'dag2', startTijd: '10:00', eindTijd: '20:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-05' }, type: 'Installatie',  sprekers: [{ _type: 'reference', _ref: 'spr-10' }, { _type: 'reference', _ref: 'spr-06' }], tags: ['Expo', 'Digitaal', 'Kunst'],         beschrijving: 'Vervolg van de groepstentoonstelling. Op dag 2 zijn de kunstenaars aanwezig voor een artist talk om 15:00.', gepubliceerd: true },
  { _id: 'evt-51', _type: 'event', titel: 'Expo: Digitale Kunstwerken (dag 3)',     dag: 'dag3', startTijd: '10:00', eindTijd: '17:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-05' }, type: 'Installatie',  sprekers: [],                                        tags: ['Expo', 'Digitaal', 'Kunst'],         beschrijving: 'Laatste dag van de groepstentoonstelling. Sluit om 17:00 — daarna afbraak.', gepubliceerd: true },
  { _id: 'evt-52', _type: 'event', titel: 'Talk: De Economie van de DJ',            dag: 'dag1', startTijd: '17:00', eindTijd: '18:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-09' }, { _type: 'reference', _ref: 'spr-11' }], tags: ['Business', 'DJ', 'Muziekindustrie'], beschrijving: 'Van gagen tot streaming royalties: Tom Bakker en Kwame Asante bespreken hoe een DJ anno 2026 zijn brood verdient.', gepubliceerd: true },
  { _id: 'evt-53', _type: 'event', titel: 'Workshop: Modulaire Synthesizers',       dag: 'dag3', startTijd: '10:00', eindTijd: '12:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-14' }, type: 'Workshop',     sprekers: [{ _type: 'reference', _ref: 'spr-14' }], tags: ['Modulair', 'Synthesizer', 'Workshop'],beschrijving: 'Een hands-on introductie in de wereld van modulaire synthesizers. Sasha Petrov neemt zijn volledige setup mee.', gepubliceerd: true },
  { _id: 'evt-54', _type: 'event', titel: 'Paneldiscussie: Muziekjournalistiek 2026',dag:'dag2', startTijd: '15:00', eindTijd: '16:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-11' }, { _type: 'reference', _ref: 'spr-07' }], tags: ['Journalistiek', 'Muziek', 'Media'],  beschrijving: 'Hoe overleeft de muziekjournalistiek in een tijdperk van algoritmen en sociale media? Kwame Asante en Rens de Groot over de toekomst van het vak.', gepubliceerd: true },
  { _id: 'evt-55', _type: 'event', titel: 'Rondleiding: Backstage TURF',            dag: 'dag1', startTijd: '13:00', eindTijd: '14:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-06' }, type: 'Rondleiding',  sprekers: [],                                        tags: ['Backstage', 'Rondleiding'],          beschrijving: 'Ga mee achter de schermen van TURF. Je ziet hoe een groot festival technisch en logistiek in elkaar steekt. Aanmelden verplicht.', aanmelding: true, gepubliceerd: true },
  { _id: 'evt-56', _type: 'event', titel: 'Live: Elektronische Kamermuziek',        dag: 'dag1', startTijd: '19:00', eindTijd: '20:30', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Performance',  sprekers: [{ _type: 'reference', _ref: 'spr-03' }, { _type: 'reference', _ref: 'spr-06' }], tags: ['Kamermuziek', 'Elektronisch', 'Intiem'],beschrijving: 'Yuki Tanaka en Sofia Blum combineren klassieke kamermuziekstructuren met elektronische geluidsproductie in een intieme concertsetting.', gepubliceerd: true },
  { _id: 'evt-57', _type: 'event', titel: 'Lichtshow: Pulse (Buiten)',              dag: 'dag2', startTijd: '20:00', eindTijd: '23:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-15' }, type: 'Installatie',  sprekers: [{ _type: 'reference', _ref: 'spr-10' }], tags: ['Lichtkunst', 'Outdoor', 'Gratis'],   beschrijving: 'De buitenversie van Ines Morales\' Pulse installatie verlicht het Wilhelminapark met interactieve lichtkunst. Gratis en vrij toegankelijk.', gratis: true, gepubliceerd: true },
  { _id: 'evt-58', _type: 'event', titel: 'Late Talk: Nacht & Stilte',              dag: 'dag2', startTijd: '21:00', eindTijd: '22:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-13' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-05' }, { _type: 'reference', _ref: 'spr-02' }], tags: ['Stilte', 'Nacht', 'Stad'],           beschrijving: 'Een avondgesprek over de waarde van stilte in de stad — en waarom nachtrumoer niet altijd de vijand is van rust.', gepubliceerd: true },
  { _id: 'evt-59', _type: 'event', titel: 'Showcase: Jonge Makers',                 dag: 'dag3', startTijd: '15:00', eindTijd: '17:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-12' }, type: 'Showcase',     sprekers: [{ _type: 'reference', _ref: 'spr-07' }], tags: ['Jonge Makers', 'Showcase', 'Talent'], beschrijving: 'Rens de Groot presenteert vijf veelbelovende Brabantse makers die voor het eerst op een groot festival staan.', gepubliceerd: true },
  { _id: 'evt-60', _type: 'event', titel: 'Borrel: Muziekindustrie Breda',          dag: 'dag1', startTijd: '18:00', eindTijd: '20:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-09' }, type: 'Workshop',     sprekers: [],                                        tags: ['Netwerken', 'Breda', 'Industrie'],   beschrijving: 'Informele borrel voor iedereen die werkzaam is in de Bredase culturele sector. Gratis drankje voor de eerste 50 aanwezigen.', gepubliceerd: true },
  { _id: 'evt-61', _type: 'event', titel: 'Midnight Outdoor: Mark',                 dag: 'dag1', startTijd: '00:00', eindTijd: '02:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-16' }, type: 'Showcase',     sprekers: [{ _type: 'reference', _ref: 'spr-04' }], tags: ['Outdoor', 'Midnight', 'Gratis'],     beschrijving: 'Een gratis outdoor muziekmoment op De Mark als aperitief voor de rest van de nacht. Amara Diallo verzorgt een set van twee uur.', gratis: true, gepubliceerd: true },
  { _id: 'evt-62', _type: 'event', titel: 'Mex: Club Night',                        dag: 'dag1', startTijd: '23:00', eindTijd: '04:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-14' }, type: 'Club Night',   sprekers: [],                                        tags: ['House', 'Club', 'Nacht'],            beschrijving: 'Mex opent haar deuren voor een avond house en funk — de warmste club van Breda doet mee aan TURF.', gepubliceerd: true },
  { _id: 'evt-63', _type: 'event', titel: 'Workshop: Zelf een Label Starten',       dag: 'dag2', startTijd: '11:00', eindTijd: '12:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-13' }, type: 'Workshop',     sprekers: [{ _type: 'reference', _ref: 'spr-08' }], tags: ['Label', 'Business', 'Workshop'],     beschrijving: 'Fatima El Idrissi deelt haar ervaring met het starten van een onafhankelijk muziekplatform: van financiering tot distributie.', gepubliceerd: true },
  { _id: 'evt-64', _type: 'event', titel: 'Performance: Human × Machine',           dag: 'dag2', startTijd: '20:00', eindTijd: '21:30', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-01' }, type: 'Performance',  sprekers: [{ _type: 'reference', _ref: 'spr-06' }, { _type: 'reference', _ref: 'spr-14' }], tags: ['AI', 'Performance', 'Mens-Machine'], beschrijving: 'Sofia Blum en Sasha Petrov spelen een live set waarbij AI-gegenereerde geluiden in real-time reageren op Sasha\'s analoge synthesizers.', gepubliceerd: true },
  { _id: 'evt-65', _type: 'event', titel: 'Nachtgesprek: Wat is Techno?',           dag: 'dag2', startTijd: '22:00', eindTijd: '23:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-12' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-12' }, { _type: 'reference', _ref: 'spr-09' }], tags: ['Techno', 'Definitie', 'Cultuur'],    beschrijving: 'Een laat nachtgesprek over de grenzen van techno als genre en als cultuur. Met Lena Fischer en Tom Bakker.', gepubliceerd: true },
  { _id: 'evt-66', _type: 'event', titel: 'Doornbos Night: Outdoor Techno',         dag: 'dag2', startTijd: '20:00', eindTijd: '01:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-18' }, type: 'Club Night',   sprekers: [{ _type: 'reference', _ref: 'spr-09' }], tags: ['Outdoor', 'Techno', 'Bos'],         beschrijving: 'Een techno nacht in het bos. Tom Bakker speelt op een geluidsinstallatie tussen de bomen van het Doornbos.', gepubliceerd: true },
  { _id: 'evt-67', _type: 'event', titel: 'Lezing: Berlijn en de Nacht',            dag: 'dag3', startTijd: '10:00', eindTijd: '11:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-13' }, type: 'Keynote',      sprekers: [{ _type: 'reference', _ref: 'spr-12' }], tags: ['Berlijn', 'Nacht', 'Geschiedenis'],  beschrijving: 'Lena Fischer over het unieke karakter van de Berlijnse nachtcultuur en de lessen die andere steden daaruit kunnen trekken.', gepubliceerd: true },
  { _id: 'evt-68', _type: 'event', titel: 'Workshop: Mix & Master',                 dag: 'dag3', startTijd: '13:00', eindTijd: '15:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-10' }, type: 'Workshop',     sprekers: [{ _type: 'reference', _ref: 'spr-09' }], tags: ['Mixing', 'Mastering', 'Workshop'],   beschrijving: 'Tom Bakker legt uit hoe hij zijn tracks mixt en mastert voor club-gebruik. Gericht op producers met enige basiskennis.', gepubliceerd: true },
  { _id: 'evt-69', _type: 'event', titel: 'Gesprek: Bredase Scenes',                dag: 'dag3', startTijd: '14:00', eindTijd: '15:30', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-07' }, { _type: 'reference', _ref: 'spr-13' }], tags: ['Breda', 'Scene', 'Lokaal'],          beschrijving: 'Rens de Groot en Noor van Dijk bespreken de opkomst van nieuwe culturele scenes in Breda — van experimenteel naar mainstream.', gepubliceerd: true },
  { _id: 'evt-70', _type: 'event', titel: 'Live: Drone & Spoken Word',              dag: 'dag3', startTijd: '16:00', eindTijd: '17:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-07' }, type: 'Performance',  sprekers: [{ _type: 'reference', _ref: 'spr-03' }, { _type: 'reference', _ref: 'spr-15' }], tags: ['Spoken Word', 'Drone', 'Live'],      beschrijving: 'Yuki Tanaka en Miriam Osei combineren drone muziek met gesproken tekst over migratie en het gevoel van nergens en overal thuis zijn.', gepubliceerd: true },
  { _id: 'evt-71', _type: 'event', titel: 'Mex: Closing Night',                     dag: 'dag3', startTijd: '22:00', eindTijd: '04:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-14' }, type: 'Club Night',   sprekers: [{ _type: 'reference', _ref: 'spr-04' }], tags: ['House', 'Funk', 'Closing'],          beschrijving: 'Amara Diallo sluit Mex af met een set die alle grenzen tussen house, funk en afro vervaagt.', gepubliceerd: true },
  { _id: 'evt-72', _type: 'event', titel: 'Skûll: Extreme Night',                   dag: 'dag3', startTijd: '23:00', eindTijd: '06:00', thema: { _type: 'reference', _ref: 'thema-night' }, locatie: { _type: 'reference', _ref: 'loc-04' }, type: 'Club Night',   sprekers: [],                                        tags: ['Hardcore', 'Experimental', 'Nacht'], beschrijving: 'Club Skûll sluit het festival af met een nacht die nergens anders past dan hier. Niet voor de gewoontedieren.', gepubliceerd: true },
  { _id: 'evt-73', _type: 'event', titel: 'Talk: De Volgende Generatie',            dag: 'dag3', startTijd: '16:30', eindTijd: '18:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-02' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-07' }, { _type: 'reference', _ref: 'spr-08' }, { _type: 'reference', _ref: 'spr-02' }], tags: ['Jeugd', 'Toekomst', 'Cultuur'], beschrijving: 'Drie jonge programmeurs, curatoren en producenten over wat hen drijft en wat ze missen in de huidige culturele sector.', gepubliceerd: true },
  { _id: 'evt-74', _type: 'event', titel: 'Afscheidsconcert: Lokaal',               dag: 'dag3', startTijd: '18:00', eindTijd: '20:00', thema: { _type: 'reference', _ref: 'thema-live' },  locatie: { _type: 'reference', _ref: 'loc-13' }, type: 'Performance',  sprekers: [{ _type: 'reference', _ref: 'spr-01' }], tags: ['Afsluiting', 'Intiem', 'Live'],      beschrijving: 'Jana Kovač sluit haar verblijf in Breda af met een intiem optreden in de kleinste zaal van het festival — voor maximaal 60 mensen.', aanmelding: true, gepubliceerd: true },
  { _id: 'evt-75', _type: 'event', titel: 'After Talk: Terug naar de Stad',         dag: 'dag3', startTijd: '20:00', eindTijd: '21:00', thema: { _type: 'reference', _ref: 'thema-talks' }, locatie: { _type: 'reference', _ref: 'loc-09' }, type: 'Panel',        sprekers: [{ _type: 'reference', _ref: 'spr-01' }, { _type: 'reference', _ref: 'spr-13' }], tags: ['Afsluiting', 'Reflectie'],           beschrijving: 'Het allerlaatste inhoudelijke moment van TURF 2026. Jana Kovač en Noor van Dijk blikken terug en vooruit. Daarna: de stad in.', gepubliceerd: true },
]

// ─── IMPORT FUNCTIE ──────────────────────────────────────────────────────────
async function importData() {
  const allDocs = [...themas, ...locaties, ...sprekers, ...events]
  let success = 0
  let failed = 0

  console.log(`\n🎵 TURF Festival — Sanity Import`)
  console.log(`📦 ${allDocs.length} documenten te importeren...\n`)

  for (const doc of allDocs) {
    try {
      await client.createOrReplace(doc)
      success++
      process.stdout.write(`✓ ${doc._type.padEnd(10)} ${doc._id.padEnd(10)} ${doc.naam ?? doc.titel ?? ''}\n`)
    } catch (err) {
      failed++
      console.error(`✗ FOUT bij ${doc._id}: ${err.message}`)
    }
  }

  console.log(`\n──────────────────────────────────`)
  console.log(`✅ Geslaagd:  ${success} documenten`)
  if (failed > 0) console.log(`❌ Mislukt:   ${failed} documenten`)
  console.log(`──────────────────────────────────`)
  console.log(`\nKlaar! Open je Sanity Studio om de data te bekijken.`)
}

importData()
